# Generated by Django 4.0 on 2022-07-24 16:29

import account.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(default='Lagos', max_length=50)),
                ('avatar_url', models.ImageField(default='profiles\x822\x07\x0e\x07vatar.png', upload_to=account.models.updload_to)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='auth.user')),
            ],
        ),
    ]
