# Generated by Django 4.0 on 2022-07-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('articles', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('video_url', models.URLField(max_length=255)),
            ],
            options={
                'verbose_name': 'Climate Education',
                'verbose_name_plural': 'Climate Education',
            },
        ),
        migrations.CreateModel(
            name='ClimateFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('url', models.URLField(max_length=255)),
            ],
            options={
                'verbose_name': 'Climate Fact',
                'verbose_name_plural': 'Climate Facts',
            },
        ),
    ]
