# Generated by Django 4.0 on 2022-07-31 14:55

from django.db import migrations, models
import edu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('articles', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=edu.models.updload_to)),
                ('video_url', models.URLField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Climate Education',
                'verbose_name_plural': 'Climate Education',
            },
        ),
        migrations.CreateModel(
            name='ClimateFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=edu.models.updload_to)),
                ('url', models.URLField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Climate Fact',
                'verbose_name_plural': 'Climate Facts',
            },
        ),
    ]
