# Generated by Django 4.0 on 2022-07-26 20:37

from django.db import migrations, models
import edu.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climateeducation',
            name='image',
            field=models.ImageField(blank=True, upload_to=edu.models.updload_to),
        ),
        migrations.AlterField(
            model_name='climatefact',
            name='image',
            field=models.ImageField(blank=True, upload_to=edu.models.updload_to),
        ),
    ]
