# Generated by Django 4.0 on 2022-07-25 14:18

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.ImageField(blank=True, upload_to=account.models.updload_to),
        ),
    ]
