# Generated by Django 4.0 on 2022-07-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_alter_climateeducation_image_alter_climatefact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climateeducation',
            name='video_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='climatefact',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
